### ISSUE TITLE
Pglet 0.4.1 not running on MacBook Air M1 (2020)

### ISSUE THREAD

**Issue by R-fred** [pglet/pglet-python#22]
Trying to run piglet leads to the process being killed straight away.
Running Python 3.9. Python installed via Homebrew.
For reference, pglet 0.3.1 ran fine, after installing 0.4.1 - same issue with 0.3.1 as with 0.4.1.

`Traceback (most recent call last):
  File "/Users/fred/Documents/_programming/Python/pglet_bellUI.py", line 1, in <module>
    import pglet
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pglet/__init__.py", line 33, in <module>
    from .pglet import *
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pglet/pglet.py", line 195, in <module>
    install()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pglet/pglet.py", line 148, in install
    installed_ver = subprocess.check_output([pglet_exe, "--version"]).decode("utf-8")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/fred/.pglet/bin/pglet', '--version']' died with <Signals.SIGKILL: 9>.
fred@Fredericks-MacBook-Air Python % /usr/local/bin/python3 /Users/fred/Documents/_programming/Python/pglet_bellUI.py
Traceback (most recent call last):
  File "/Users/fred/Documents/_programming/Python/pglet_bellUI.py", line 1, in <module>
    import pglet
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pglet/__init__.py", line 33, in <module>
    from .pglet import *
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pglet/pglet.py", line 195, in <module>
    install()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pglet/pglet.py", line 148, in install
    installed_ver = subprocess.check_output([pglet_exe, "--version"]).decode("utf-8")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/fred/.pglet/bin/pglet', '--version']' died with <Signals.SIGKILL: 9>.`

**Comment by FeodorFitsner** [comment]
What do you get if run `/Users/fred/.pglet/bin/pglet --version` in the console directly?

**Comment by R-fred** [comment]
I get the following
`Users/fred/.pglet/bin/pglet --version
zsh: killed     /Users/fred/.pglet/bin/pglet --version

ls -l /Users/fred/.pglet 
total 0
drwxr-xr-x  5 fred  staff  160 May 12 01:02 bin
fred@Fredericks-MacBook-Air Python % ls -l /Users/fred/.pglet/bin
total 47312
-rw-r--r--  1 fred  staff     34523 May 23 02:20 LICENSE
-rw-r--r--  1 fred  staff      3720 May 23 02:20 README.md
-rwxr-xr-x  1 fred  staff  23772706 May 23 02:26 pglet`

**Comment by FeodorFitsner** [comment]
Could you try downloading https://github.com/pglet/pglet/releases/download/v0.4.1/pglet-0.4.1-darwin-arm64 (it's executable, not an archive) and run it with `--version` arg?

**Comment by R-fred** [comment]
I ended up reinstalling python from python.org and reinstalling pglet after that. Now everything seems to work fine.

```
% /Users/fred/.pglet/bin/pglet --version                                 
0.4.1%     
```

**Comment by FeodorFitsner** [comment]
Interesting. Could it be that Python was working in Rosetta mode and as a result Pglet module pulling wrong executable (believing it's x86 arch)?

**Comment by R-fred** [comment]
Not sure, but it could well be, the python.org installer is a universal installer.
I also tried removing the .pglet folder in my home folder before reinstalling with Homebrew. Homebrew did not install pglet in the home directory leading to failure.
Using the python version from python.org, no problems at all.

**Comment by FeodorFitsner** [comment]
OK, cool, glad you managed to resolve it and I don't need to rent Apple Sillicon M1 :)
There were some changes into 4.x release, i.e. `web` parameter in `pglet.page()` and `pglet.app()` has gone and replaced with `local`. By default the app runs on https://console.pglet.com, to use local dev server use `local=True`. I'm going to write a blog post today/tomorrow.

**Comment by R-fred** [comment]
Thanks @FeodorFitsner. I am closing the issue since it is resolved.
