### ISSUE TITLE
timeout error on MacBook M1

### ISSUE THREAD

**Issue by R-fred** [pglet/pglet-python#55]
I am getting a timeout error (using version 0.5.8) that I was not getting with version 0.4.4.

Did something change in 0.5?

Hardware: MacBook Air M1 running MacOS 12.1 and python 3.9.5.

I get the following error:
```python
Starting Pglet Server in local mode...
Traceback (most recent call last):
  File "/Users/fred/Documents/_programming/Python/Hello_xxx/pglet_linechart.py", line 74, in <module>
    pglet.app("python-linechart", target=main, local=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pglet/pglet.py", line 35, in app
    conn = _connect_internal(name, True, web, server, token, permissions, no_window, target)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pglet/pglet.py", line 119, in _connect_internal
    raise Exception(f"Could not connected to Pglet server in {CONNECT_TIMEOUT_SECONDS} seconds.")
Exception: Could not connected to Pglet server in 30 seconds.
```

Here is the code I am trying to run:
```python
import datetime
import random
import time

import pglet
from pglet import Text, LineChart
from pglet.linechart import Data, Point

def main(page):

    # simple line chart with numbers on X axis
    simple_chart = LineChart(legend=True, tooltips=True, stroke_width=4, y_min=0, y_max=100, y_format='{y}%', 
            x_type='number', width='500', height='300px', lines=[
                Data(legend='Line 1', points=[
                    Point(x=0, y=0),
                    Point(x=1, y=10),
                    Point(x=2, y=20),
                    Point(x=3, y=50),
                    Point(x=4, y=100),
                    Point(x=5, y=90),
                    Point(x=6, y=50),
                    Point(x=7, y=30),
                    Point(x=8, y=20),
                    Point(x=9, y=5)
                ])
            ])

    # two lines on the same chart
    multi_chart = LineChart(legend=True, tooltips=True, stroke_width=4, y_ticks=5, y_min=0, y_max=100, y_format='{y}%', 
            x_type='number', width='500', height='400px', lines=[])

    line1 = Data(legend='Line 1', color='Orange')
    line2 = Data(legend='Line 2', color='Magenta')
    for i in range (0, 21):
        line1.points.append(Point(x=i, y=random.random() * 100))
        line2.points.append(Point(x=i, y=random.random() * 100))
    multi_chart.lines.append(line1)
    multi_chart.lines.append(line2)

    # negative values with time on X axis
    temp_chart = LineChart(legend=True, tooltips=True, y_ticks=4, y_min=-20, y_max=20, y_format='{y} °C', 
            x_type='date', width='500px', height='400px', lines=[
                Data(color='green', legend='t, °C')
            ])
    start_date = datetime.datetime(2021, 4, 1, 10, 5)
    m = 0
    for i in range(0, 60):
        d = start_date + datetime.timedelta(minutes=m)
        v = round((random.random() - 0.5) * 40)
        temp_chart.lines[0].points.append(Point(x=d, y=v))
        m += 1

    page.add(
        Text("Simple line chart with numbers on X axis", size='xLarge'),
        simple_chart,

        Text("Line chart with two lines", size='xLarge'),
        multi_chart,

        Text("Negative values with time on X axis", size='xLarge'),
        temp_chart        
    )

    # simulate "running" chart
    while(True):
        d = start_date + datetime.timedelta(minutes=m)
        v = round((random.random() - 0.5) * 40)
        temp_chart.lines[0].points.pop(0)
        temp_chart.lines[0].points.append(Point(x=d, y=v))    
        m += 1
        page.update()
        time.sleep(1)

pglet.app("python-linechart", target=main, local=True)
```

**Comment by FeodorFitsner** [comment]
It's probably because port 5000 is taken in macOS Monterey be default: https://utf9k.net/questions/macos-port-5000-monterey/

**Comment by R-fred** [comment]
Is it possible to set the port? Do I remember correctly that this is done via an environment variable?

**Comment by FeodorFitsner** [comment]
Yep, it's `PGLET_SERVER_PORT`.

**Comment by R-fred** [comment]
setting the environment variable to 5001 before running the app worked like a charm :)

**Comment by FeodorFitsner** [comment]
Thanks for the update! We are going to change default port to `8550`: https://github.com/pglet/pglet/issues/120
